--
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
-- @generated
--


require 'Thrift'
require 'shared_constants'

SharedStruct = __TObject:new{
  key,
  value
}

function SharedStruct:read(iprot)
  iprot:readStructBegin()
  while true do
    local fname, ftype, fid = iprot:readFieldBegin()
    if ftype == TType.STOP then
      break
    elseif fid == 1 then
      if ftype == TType.I32 then
        self.key = iprot:readI32()
      else
        iprot:skip(ftype)
      end
    elseif fid == 2 then
      if ftype == TType.STRING then
        self.value = iprot:readString()
      else
        iprot:skip(ftype)
      end
    else
      iprot:skip(ftype)
    end
    iprot:readFieldEnd()
  end
  iprot:readStructEnd()
end

function SharedStruct:write(oprot)
  oprot:writeStructBegin('SharedStruct')
  if self.key then
    oprot:writeFieldBegin('key', TType.I32, 1)
    oprot:writeI32(self.key)
    oprot:writeFieldEnd()
  end
  if self.value then
    oprot:writeFieldBegin('value', TType.STRING, 2)
    oprot:writeString(self.value)
    oprot:writeFieldEnd()
  end
  oprot:writeFieldStop()
  oprot:writeStructEnd()
end