--
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
-- @generated
--


require 'Thrift'

INT32CONSTANT = 9853

MAPCONSTANT = {
  ['hello'] = 'world',
  ['goodnight'] = 'moon'
}